---

- name: prebootstrap-role
  src: https://github.com/hmcts/prebootstrap-role.git
  scm: git
  version: master

- name: devops.filebeat
  src: https://github.com/hmcts/filebeat-role.git
  scm: git
  version: master

- name: clamav-role
  src: https://github.com/hmcts/clamav-role
  scm: git
  version: master

- name: zabbixagent-role
  src: https://github.com/hmcts/zabbixagent-role
  scm: git
  version: master

- name: repos-role
  src: https://github.com/hmcts/repos-role.git
  scm: git
  version: master
