---
- set_fact:
    operating_system: "Linux"
  when: ansible_os_family != 'Windows'

- set_fact:
    operating_system: "Windows"
  when: ansible_os_family == 'Windows'

- name: Include tasks for the corresponding operating system
  include_tasks: "{{ operating_system }}/main.yml"
