---
- name: Select the dynamic passwordless_sudo list based on toggle.
  set_fact: passwordless_sudo="{{ passwordless_sudo_dynamic }}"
  when: passwordless_sudo_type == "dynamic"

- name: Select the static passwordless_sudo list based on toggle.
  set_fact: passwordless_sudo="{{ passwordless_sudo_static }}"
  when: passwordless_sudo_type == "static"

- name: "Enable passwordless sudo"
  template:
    src: templates/passwordless_sudo.j2
    dest: "/etc/sudoers.d/{{ item }}"
  with_items: "{{ passwordless_sudo }}"
  tags:
    - passwordless_sudo
