---
- name: restart postfix
  service: name=postfix state=restarted

- name: restart ntp
  service: "name={{ ntp_daemon }} state=restarted"
  when: ntp_enabled

- name: reinit systemd
  command: systemctl daemon-reexec

- name: restart waagent
  service:
    name: waagent
    state: restarted
