---
- name: Install Windows Server 2016 Containers feature
  win_feature:
    name: Containers # required. Names of roles or features to install as a single feature or a comma-separated list of features.
    include_sub_features: yes # not required. Adds all subfeatures of the specified feature.
    state: present # not required. choices: present;absent. State of the features or roles on the system.

- name: Removed unused Windows features
  win_feature:
    name: 
    - FS-SMB1
    state: absent

- name: Set Proxy machine level
  win_environment:
    state: present
    name: HTTP_PROXY
    value: http://reformMgmtProxyOut.reform.hmcts.net:8080
    level: machine

- name: Set Proxy machine level
  win_environment:
    state: present
    name: HTTPS_PROXY
    value: http://reformMgmtProxyOut.reform.hmcts.net:8080
    level: machine

- name: Install docker engine
  win_shell: |   
   If (!((Get-Service Docker -ErrorAction SilentlyContinue).Status -eq "running")) {
    $proxyString = "http://reformMgmtProxyOut.reform.hmcts.net:8080"
    $proxyUri = new-object System.Uri($proxyString)
    [System.Net.WebRequest]::DefaultWebProxy =
    new-object System.Net.WebProxy ($proxyUri, $true)

    set proxy proxy-server="http=http://reformMgmtProxyOut.reform.hmcts.net:8080;https=http://reformMgmtProxyOut.reform.hmcts.net:8080"
    Write-Output "Installing Docker engine"
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force -Verbose -Proxy http://reformMgmtProxyOut.reform.hmcts.net:8080
    Install-Module -Name DockerMsftProvider -Repository PSGallery -Force -Verbose
    Install-Package Docker -ProviderName DockerMsftProvider -Force -verbose
    Write-Verbose "Restarting machine" -Verbose
    Restart-Computer -Force
    }
    else {Write-Output "Docker engine installed " -Verbose}
